const APP_BASE_PATH = 'http://localhost:1234';

module.exports = {
  'User signin': (browser) => {
    browser
      .url(APP_BASE_PATH)
      .waitForElementVisible('body', 5000)
      .assert.urlEquals(`${APP_BASE_PATH}/`)
      .assert.visible('body')
      .click('.sign-in-lk')
      .waitForElementVisible('.signin-page', 5000)
      .assert.visible('.signin-page')
      .assert.visible('.sign-in-container')
      .setValue('.email', 'efosa@gmail.com')
      .pause(1000)
      .setValue('.password-signin', 'testers')
      .pause(1000)
      .click('.btn-submit')
      .waitForElementVisible('.no-events', 5000)
      .pause(2500)
      .click('.btn-add-event-e')
      .waitForElementVisible('.add-event-form', 5000)
      .assert.visible('.add-event-form')
      .pause(1000)
      .click('.btn-add')
      .waitForElementVisible('.swal-button', 3000)
      .assert.visible('.swal-button')
      .pause(1000)
      .click('.swal-button')
      .pause(1000)
      .setValue('.name', 'First Event')
      .pause(1000)
      .click('select[name=type]')
      .pause(1000)
      .click('option[value=Conference]')
      .pause(1000)
      .setValue('input[name=startDate]', '20/06/2018')
      .pause(1000)
      .setValue('input[name=endDate]', '21/06/2018')
      .pause(1000)
      .setValue('select[name=center]', 'Greatest Center')
      .pause(1000)
      .click('.btn-add')
      .waitForElementVisible('.acenter', 3000)
      .assert.visible('.acenter')
      .pause(2000)
      .click('.add-event-nav')
      .waitForElementVisible('.add-event-form', 5000)
      .pause(1000)
      .setValue('.name', 'Second Event')
      .pause(1000)
      .click('select[name=type]')
      .pause(1000)
      .click('option[value=Conference]')
      .pause(1000)
      .setValue('input[name=startDate]', '22/06/2018')
      .pause(1000)
      .setValue('input[name=endDate]', '23/06/2018')
      .pause(1000)
      .setValue('select[name=center]', 'Greatest Center')
      .pause(1000)
      .click('.btn-add')
      .waitForElementVisible('.acenter', 3000)
      .assert.visible('.acenter')
      .pause(2500)
      .click('.mod-btn')
      .waitForElementVisible('.modify-event-form', 5000)
      .pause(1000)
      .clearValue('.name')
      .setValue('.name', 'Modified Event')
      .pause(1000)
      .setValue('select[name=center]', 'Nicest Center')
      .pause(1000)
      .click('.btn-modify')
      .waitForElementVisible('.acenter', 3000)
      .pause(1000)
      .click('.btn-outline-danger')
      .pause(2000)
      .click('.swal-button--cancel')
      .pause(2000)
      .click('.btn-outline-danger')
      .pause(1000)
      .click('.swal-button--confirm')
      .pause(5000)
      .click('.detail-btn')
      .waitForElementVisible('.modal-sm', 5000)
      .pause(4000)
      .click('.close')
      .pause(1000)
      .setValue('.search-lg', 'Gr')
      .pause(2000)
      .click('.btn-search-lg')
      .waitForElementVisible('.acenter', 5000)
      .assert.visible('.form-search')
      .assert.visible('.acenter')
      .pause(1000)
      .click('.detail-btn')
      .waitForElementVisible('.img-oneCenter', 5000)
      .assert.visible('.img-oneCenter')
      .pause(1000)
      .click('.btn-facilities')
      .pause(2000)
      .click('.btn-close-f')
      .pause(1000)
      .click('.btn-booked-dates')
      .pause(2000)
      .click('.btn-close-b')
      .pause(1500)
      .click('.btn-book')
      .waitForElementVisible('.add-event-form', 5000)
      .assert.visible('.add-event-form')
      .pause(1000)
      .click('.events-link')
      .waitForElementVisible('.acenter', 5000)
      .pause(3000)
      .end();
  }
};

