const path = require('path');
const APP_BASE_PATH = 'http://localhost:1234';

module.exports = {
  'User signin': (browser) => {
    browser
      .url(APP_BASE_PATH)
      .waitForElementVisible('body', 5000)
      .assert.urlEquals(`${APP_BASE_PATH}/`)
      .assert.visible('body')
      .click('.sign-in-lk')
      .waitForElementVisible('.signin-page', 5000)
      .assert.visible('.signin-page')
      .assert.visible('.sign-in-container')
      .setValue('.email', 'efosaokpugie@gmail.com')
      .pause(1000)
      .setValue('.password-signin', 'swampious')
      .pause(1000)
      .click('.btn-submit')
      .waitForElementVisible('.all-centers', 5000)
      .assert.visible('.all-centers')
      .pause(2500)
      .click('.add-center-nav')
      .waitForElementVisible('.add-center-form-one', 5000)
      .assert.visible('.add-center-form-one')
      .setValue('.name', 'Grande')
      .pause(500)
      .setValue('select[name=type]', 'Wedding hall')
      .pause(500)
      .setValue('input[name=capacity]', 23000)
      .pause(500)
      .setValue('input[name=address]', '235, Ikorodu road, Ilupeju')
      .pause(500)
      .setValue('input[name=mobileNumber]', '08035272406')
      .pause(500)
      .click('.btn-add')
      .waitForElementVisible('.add-center-form-one', 5000)
      .assert.visible('.add-center-form-one')
      .pause(1000)
      .click('input[name=lounge]')
      .pause(500)
      .click('input[name=swimming-pool]')
      .pause(500)
      .setValue('input[name=rentalCost]', 23000000)
      .pause(500)
      .click('.fa-chevron-right')
      .waitForElementVisible('.add-center-form-one', 5000)
      .assert.visible('.add-center-form-one')
      .pause(1000)
      .click('input[name=imageFile]')
      .setValue('input[name=imageFile]', path.resolve(`${__dirname}/landingimg.jpg`))
      .waitForElementVisible('.upload-btn', 5000)
      .assert.visible('.upload-btn')
      .click('.upload-btn')
      .waitForElementVisible('.btn-addcenter', 1000000)
      .assert.visible('.btn-addcenter')
      .click('.btn-addcenter')
      .waitForElementVisible('.all-centers', 5000)
      .assert.visible('.all-centers')
      .pause(2500)
      .click('.modify-btn')
      .waitForElementVisible('.modify-center', 5000)
      .assert.visible('.modify-center')
      .pause(1000)
      .clearValue('.name')
      .setValue('.name', 'Very Grande')
      .pause(500)
      .setValue('select[name=type]', 'Club')
      .pause(500)
      .click('.btn-save-m')
      .waitForElementVisible('.all-centers', 5000)
      .assert.visible('.all-centers')
      .pause(2500)
      .useXpath()
      .click('(//button[@class="btn edit-btn center-btn detail-btn"])[3]')
      .useCss()
      .waitForElementVisible('.img-oneCenter', 5000)
      .assert.visible('.img-oneCenter')
      .pause(1000)
      .click('.btn-booked-dates')
      .pause(1000)
      .click('.btn-cancel')
      .pause(8000)
      .click('.btn-close-b')
      .pause(1000)
      .click('.grant-users-nav')
      .waitForElementVisible('.all-users-page', 5000)
      .assert.visible('.all-users-page')
      .pause(1000)
      .click('.btn-upgrade')
      .pause(4500)
      .click('.btn-downgrade')
      .pause(3000)
      .end();
  }
};

